### ISSUE TITLE
Support for automatic initialization of SDK on App startup

### ISSUE THREAD

**Issue by PatilShreyas** [Gappein/Gappein-Chat-SDK#12]
It's a great library and that's why I would like to suggest an improvement which can be done here in this SDK. 

### Proposed solution
- Just like official Firebase SDK doesn't need manual initialization (as it's optional, we can do that but it's not needed). We can do the same here with the help of `ContentProvider`.
- Whenever the app is launched, SDK will be automatically initialized on app startup.

### Advantage
- Developer won't need to call `initialize()` manually.

### Reference:
- https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html

---

I hope you'll find this suggestion helpful.

**Comment by darshanpania** [comment]
@PatilShreyas We're honored that you've opened our first Github issue. 🙏 

Thank you for the suggestion of using Firebase style Content Provider to initialize the library. Personally, I'm on the fence about it. Since all Content Providers are started when the Application class is initialized, it could lead to performance bottlenecks. We've gone with the manual `initialize()` approach so that we do not add to that problem. 
What are your thoughts on Content Providers vs [App-Startup Library](https://developer.android.com/topic/libraries/app-startup)?
I'll also let @hi-manshu also chime in for his suggestions.

**Comment by PatilShreyas** [comment]
Thanks @darshanpania.

Yeah you're right. And I also thought about App startup library but currently it's not stable so I thought it would be not good to use. Internally app startup library also uses `ContentProvider` under the hood.

**Comment by hi-manshu** [comment]
Thanks @PatilShreyas , I would like to say as we get granularity of controlling as developers on the SDK, we kept initialize() method there.

As we are planning a lot of things where user should have some sort of custom requirement, there this method would come useful.

**Comment by PatilShreyas** [comment]
Thanks, @hi-manshu for the explanation.
